// Generated by CoffeeScript 1.6.2
(function() {
  var SERVER_HOST, SERVER_PORT, clickOnGooglePlayButton, commands, init, runOnGooglePlay, socket;

  SERVER_PORT = 8123;

  SERVER_HOST = "127.0.0.1:" + SERVER_PORT;

  socket = null;

  init = function() {
    socket = io.connect(SERVER_HOST);
    socket.emit("extension", null);
    socket.on("music", function(command) {
      console.debug("Got command " + command);
      return commands[command]();
    });
    return console.debug("Web Music Remote initialized");
  };

  runOnGooglePlay = function(code) {
    return chrome.tabs.query({
      url: "*://play.google.com/music*"
    }, function(tabs) {
      var tabId;

      if (tabs && tabs.length > 0) {
        console.debug("Found " + tabs.length + " google play tabs");
        tabId = tabs[0].id;
        return chrome.tabs.executeScript(tabId, {
          code: code
        });
      }
    });
  };

  clickOnGooglePlayButton = function(id) {
    var code;

    code = ("console.log('clicking on " + id + "'); ") + ("document.querySelector(\"button[data-id='" + id + "']\").click()");
    return runOnGooglePlay(code);
  };

  commands = {
    play: function() {
      console.debug("Playing");
      return clickOnGooglePlayButton('play-pause');
    },
    next: function() {
      console.debug("Next");
      return clickOnGooglePlayButton('forward');
    },
    prev: function() {
      console.debug("Prev");
      return clickOnGooglePlayButton('rewind');
    }
  };

  console.debug("Web Music Remote loaded");

  window.onload = init;

}).call(this);
